### ISSUE TITLE
Error on Windows: AWS authentication requires a valid Date or x-amz-date header

### ISSUE THREAD

**Issue by davisengeler** [davisengeler/big-data-virus-analysis#1]
I'm currently getting `AWS authentication requires a valid Date or x-amz-date header` when trying to compile and run via `sbt` on Windows. I'll look into it.

**Comment by davisengeler** [comment]
I'm not sure if this would be helpful, but here's my Java version:

```
java version "1.8.0_73"
Java(TM) SE Runtime Environment (build 1.8.0_73-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.73-b02, mixed mode)
```

**Comment by alexsniffin** [comment]
I'd recommend using the recommended 1.7 Java version for our project. If I'm correct Scala 2.10.x is only compatible with Java 1.7. 

I'm not quiet familiar with running SBT and AWS on windows, but I think this error is from a library issue. Try adding:

`libraryDependencies += "joda-time" % "joda-time" % "2.9.2"`

to your build.sbt file.

**Comment by davisengeler** [comment]
I tried adding that line of code before downgrading Java, but to no avail. I downgraded Java and it seems to work fine now, even without the line you suggested in `build.sbt`. Thanks for the suggestions!
